spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      datasource:
        #多数据源
        master:
          url: "jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave:
#          url:
#          username:
#          password:
#          driver-class-name: com.mysql.cj.jdbc.Driver
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
